# Schema for the configuration files of the Entity Reference module.

entity_reference.default.handler_settings:
  type: mapping
  label: 'View handler settings'
  mapping:
    target_bundles:
      type: sequence
      label: 'types'
      sequence:
        - type: string
          label: 'Type'
    sort:
      type: mapping
      label: 'Sort settings'
      mapping:
        field:
          type: string
          label: 'Sort by'
        direction:
          type: string
          label: 'Sort direction'
    filter:
      type: mapping
      label: 'Filter settings'
      mapping:
        type:
          type: string
          label: 'Filter by'
        role:
          type: sequence
          label: 'Restrict to the selected roles'
          sequence:
            - type: string
              label: 'Role'
    auto_create:
      type: boolean
      label: 'Create referenced entities if they don''t already exist'

field.formatter.settings.entity_reference_entity_view:
  type: mapping
  label: 'Entity reference rendered entity display format settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'
    link:
      type: boolean
      label: 'Show links'

field.formatter.settings.entity_reference_entity_id:
  type: mapping
  label: 'Entity reference entity ID display format settings'

field.formatter.settings.entity_reference_label:
  type: mapping
  label: 'Entity reference label display format settings'
  mapping:
    link:
      type: boolean
      label: 'Link label to the referenced entity'

field.widget.settings.entity_reference_autocomplete_tags:
  type: mapping
  label: 'Entity reference autocomplete (Tags style) display format settings'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    autocomplete_type:
      type: string
      label: 'Autocomplete type'
    placeholder:
      type: label
      label: 'Placeholder'

field.widget.settings.entity_reference_autocomplete:
  type: mapping
  label: 'Entity reference autocomplete display format settings'
  mapping:
    match_operator:
      type: string
      label: 'Autocomplete matching'
    size:
      type: integer
      label: 'Size of textfield'
    autocomplete_type:
      type: string
      label: 'Autocomplete type'
    placeholder:
      type: label
      label: 'Placeholder'
