---
Name: modelascontrollerroutes
After: framework/routes#rootroutes
---
Director:
  rules:
    '': 'RootURLController'
    '$URLSegment//$Action/$ID/$OtherID': 'ModelAsController'
---
Name: legacycmsroutes
After: '*'
---
Director:
  rules:
    'admin/cms': '->admin/pages'