# Schema for the migrate source plugins.

migrate.source.*:
  type: migrate_source
  label: 'Default source'

migrate.source.empty:
  type: migrate_source_sql
  label: 'Empty source'
  mapping:
    provider:
      type: string
      label: 'Provider'
    constants:
      type: mapping
      label: 'Constants'
      mapping:
        entity_type:
          type: string
          label: 'Entity type'
        type:
          type: string
          label: 'Type'
        name:
          type: string
          label: 'Name'
        cardinality:
          type: integer
          label: 'Cardinality'
        display_field:
          type: boolean
          label: 'Display field'
