# Schema for the configuration files of the Datetime module.

field.storage_settings.datetime:
  type: mapping
  label: 'Datetime settings'
  mapping:
    datetime_type:
      type: string
      label: 'Date type'

field.field_settings.datetime:
  type: mapping
  label: 'Datetime settings'

field.value.datetime:
  type: mapping
  label: 'Default value'
  mapping:
    default_date_type:
      type: string
      label: 'Default date type'
    default_date:
      type: string
      label: 'Default date value'

field.formatter.settings.datetime_default:
  type: mapping
  label: 'Datetime default display format settings'
  mapping:
    format_type:
      type: string
      label: 'Date format'

field.formatter.settings.datetime_plain:
  type: mapping
  label: 'Datetime plain display format settings'

field.widget.settings.datetime_datelist:
  type: mapping
  label: 'Datetime select list display format settings'
  mapping:
    increment:
      type: integer
      label: 'Time increments'
    date_order:
      type: string
      label: 'Date part order'
    time_type:
      type: string
      label: 'Time type'

field.widget.settings.datetime_default:
  type: mapping
  label: 'Datetime default display format settings'
