name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2014-12-17
version: '8.0.0-beta4'
core: '8.x'
project: 'drupal'
datestamp: 1418825451
